name: CI/CD

on:
  pull_request:
    branches:
      - main
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Run unit tests
          run: ./gradlew test